export const vowelQuestions = [
  {
    question: 'How many vowels in "HARP"?',
    options: [
      {id: 'A', text: '2'},
      {id: 'B', text: '1'},
      {id: 'C', text: '4'},
      {id: 'D', text: '5'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vowels/1.jpeg'),
  },
  {
    question: 'Find missing vowels "_Q__R__M" (aquarium).',
    options: [
      {id: 'A', text: 'A,U,A,I,U'},
      {id: 'B', text: 'A,U,E,I,Y'},
      {id: 'C', text: 'I,U,I,E,I'},
      {id: 'D', text: 'E,A,Y,U,A'},
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/vowels/2.jpeg'),
  },
  {
    question: 'Count the vowels of given picture.',
    options: [
      {id: 'A', text: '6'},
      {id: 'B', text: '2'},
      {id: 'C', text: '3'},
      {id: 'D', text: '5'},
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/vowels/3.jpeg'),
  },
  {
    question: 'Find the vowel in "KNIGHT".',
    options: [
      {id: 'A', text: 'I'},
      {id: 'B', text: 'K'},
      {id: 'C', text: 'G'},
      {id: 'D', text: 'T'},
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/vowels/4.jpeg'),
  },
  {
    question: 'Find missing vowels "SW_N".',
    options: [
      {id: 'A', text: 'E'},
      {id: 'B', text: 'I'},
      {id: 'C', text: 'Y'},
      {id: 'D', text: 'A'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vowels/5.jpeg'),
  },
  {
    question: 'Write missing vowels "_C_L_ND".',
    options: [
      {id: 'A', text: 'I , E , A'},
      {id: 'B', text: 'A ,I ,E'},
      {id: 'C', text: 'A ,O,U'},
      {id: 'D', text: 'A , U, I'},
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/vowels/6.jpeg'),
  },
  {
    question: 'In the word "GARDEN" which vowel has a long sound?',
    options: [
      {id: 'A', text: 'E'},
      {id: 'B', text: 'A'},
      {id: 'C', text: 'I'},
      {id: 'D', text: 'U'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vowels/7.jpeg'),
  },
  {
    question: 'Count vowels of given word "OCTOPUS" (vowels which are not repeated).',
    options: [
      {id: 'A', text: '2'},
      {id: 'B', text: '5'},
      {id: 'C', text: '3'},
      {id: 'D', text: '4'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vowels/8.jpeg'),
  },
  {
    question: 'Count vowels of given word "DOLPHIN".',
    options: [
      {id: 'A', text: '2'},
      {id: 'B', text: '3'},
      {id: 'C', text: '5'},
      {id: 'D', text: '1'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vowels/9.jpeg'),
  },
  {
    question: 'Find missing vowels "ST_R F_SH".',
    options: [
      {id: 'A', text: 'O,I'},
      {id: 'B', text: 'A,I'},
      {id: 'C', text: 'E,A'},
      {id: 'D', text: 'E,U'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vowels/10.jpeg'),
  },
  {
    question: 'Count vowels of given word "UMBRELLA".',
    options: [
      {id: 'A', text: '1'},
      {id: 'B', text: '2'},
      {id: 'C', text: '3'},
      {id: 'D', text: '5'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vowels/11.jpeg'),
  },
  {
    question: 'Fill missing vowels sequence "G_R_FF_".',
    options: [
      {id: 'A', text: 'A , E , I'},
      {id: 'B', text: 'I , A ,E'},
      {id: 'C', text: 'I , E , A'},
      {id: 'D', text: 'A , U , I'},
    ],
    correctAnswer: 'C',
    image: require('../Utils/Images/Images/vowels/12.jpeg'),
  },
  {
    question: 'Count vowels of given word "SEA HORSE".',
    options: [
      {id: 'A', text: '7'},
      {id: 'B', text: '3'},
      {id: 'C', text: '4'},
      {id: 'D', text: '2'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vowels/13.jpeg'),
  },
  {
    question: 'Complete the word using correct sequence of vowels "_N_C_RN".',
    options: [
      {id: 'A', text: 'A , E , O'},
      {id: 'B', text: 'I , O , U'},
      {id: 'C', text: 'A , U , O'},
      {id: 'D', text: 'U , I , O'},
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/vowels/14.jpeg'),
  },
  {
    question: 'How many times "A" and "O" vowel come in the word "KANGAROO".',
    options: [
      {id: 'A', text: '1 time'},
      {id: 'B', text: '2 times each'},
      {id: 'C', text: '4 times'},
      {id: 'D', text: 'Both b and c option'},
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/vowels/15.jpeg'),
  },
  {
    question: 'Fill missing vowels of given bird "_STR_CH".',
    options: [
      {id: 'A', text: 'O , I'},
      {id: 'B', text: 'E , A'},
      {id: 'C', text: 'U ,O'},
      {id: 'D', text: 'E ,I'},
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/vowels/16.png'),
  },
  {
    question: 'First and last vowel of "_YEST_R".',
    options: [
      {id: 'A', text: 'Y , E'},
      {id: 'B', text: 'I ,A'},
      {id: 'C', text: 'O , E'},
      {id: 'D', text: 'A , O'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vowels/17.jpeg'),
  },
  {
    question: 'Find the middle vowel of fruit "PRES_MMON".',
    options: [
      {id: 'A', text: 'A'},
      {id: 'B', text: 'I'},
      {id: 'C', text: 'E'},
      {id: 'D', text: 'O'},
    ],
    correctAnswer: 'C',
    image: require('../Utils/Images/Images/vowels/18.jpeg'),
  },
  {
    question: 'Count the vowels used in word "PITAYA" (not repeated).',
    options: [
      {id: 'A', text: '1'},
      {id: 'B', text: '2'},
      {id: 'C', text: '6'},
      {id: 'D', text: '3'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vowels/19.jpeg'),
  },
  {
    question: '"ANTELOPE" has __ number of vowels.',
    options: [
      {id: 'A', text: '4'},
      {id: 'B', text: '7'},
      {id: 'C', text: '3'},
      {id: 'D', text: '2'},
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/vowels/20.jpeg'),
  },
    {
      question: 'Second and last vowels in “C_STL_”.',
      options: [
        {id: 'A', text: 'A , I'},
        {id: 'B', text: 'E , I'},
        {id: 'C', text: 'O , U'},
        {id: 'D', text: 'A  , E'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vowels/21.jpeg'),
    },
    {
      question: 'Click second vowel of picture.',
      options: [
        {id: 'A', text: 'I'},
        {id: 'B', text: 'O'},
        {id: 'C', text: 'A'},
        {id: 'D', text: 'U'},
      ],
      correctAnswer: 'A',
      image: require('../Utils/Images/Images/vowels/22.jpeg'),
    },
    {
      question: 'Which vowel will use in given word “CH_RRY”.',
      options: [
        {id: 'A', text: 'A'},
        {id: 'B', text: 'E'},
        {id: 'C', text: 'O'},
        {id: 'D', text: 'I'},
      ],
      correctAnswer: 'A',
      image: require('../Utils/Images/Images/vowels/23.jpeg'),
    },
    {
      question: '“Daffodil” has __ number of vowels.',
      options: [
        {id: 'A', text: '3'},
        {id: 'B', text: '5'},
        {id: 'C', text: '2'},
        {id: 'D', text: '1'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vowels/24.jpeg'),
    },
    {
      question: 'Fill the second last alphabet of picture.',
      options: [
        {id: 'A', text: 'A'},
        {id: 'B', text: 'I'},
        {id: 'C', text: 'O'},
        {id: 'D', text: 'E'},
      ],
      correctAnswer: 'D',
      image: require('../Utils/Images/Images/vowels/25.jpeg'),
    },
    {
      question: 'Find short sound letter in “BROCCOLI”.',
      options: [
        {id: 'A', text: 'B'},
        {id: 'B', text: 'I'},
        {id: 'C', text: 'O'},
        {id: 'D', text: 'L'},
      ],
      correctAnswer: 'C',
      image: require('../Utils/Images/Images/vowels/26.jpeg'),
    },
    {
      question: 'Picture has _ as first letter.',
      options: [
        {id: 'A', text: 'I'},
        {id: 'B', text: 'O'},
        {id: 'C', text: 'A'},
        {id: 'D', text: 'E'},
      ],
      correctAnswer: 'C',
      image: require('../Utils/Images/Images/vowels/27.jpeg'),
    },
    {
      question: 'Count vowels in “PAPAYA”.',
      options: [
        {id: 'A', text: '1'},
        {id: 'B', text: '2'},
        {id: 'C', text: '4'},
        {id: 'D', text: '3'},
      ],
      correctAnswer: 'D',
      image: require('../Utils/Images/Images/vowels/28.jpeg'),
    },
    {
      question: 'Click the last letter of picture.',
      options: [
        {id: 'A', text: 'A'},
        {id: 'B', text: 'E'},
        {id: 'C', text: 'I'},
        {id: 'D', text: 'U'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vowels/29.jpeg'),
    },
    {
      question: 'Last vowel of picture.',
      options: [
        {id: 'A', text: 'I'},
        {id: 'B', text: 'O'},
        {id: 'C', text: 'U'},
        {id: 'D', text: 'E'},
      ],
      correctAnswer: 'D',
      image: require('../Utils/Images/Images/vowels/30.jpeg'),
    },
    {
      question: 'Fill vowel in missing place “K_W_”.',
      options: [
        {id: 'A', text: 'I , I'},
        {id: 'B', text: 'E , I'},
        {id: 'C', text: 'I , E'},
        {id: 'D', text: 'O  , A'},
      ],
      correctAnswer: 'C',
      image: require('../Utils/Images/Images/vowels/31.jpeg'),
    },
    {
      question: 'Find silent vowel.',
      options: [
        {id: 'A', text: 'E'},
        {id: 'B', text: 'A'},
        {id: 'C', text: 'O'},
        {id: 'D', text: 'U'},
      ],
      correctAnswer: 'A',
      image: require('../Utils/Images/Images/vowels/32.jpeg'),
    },
    {
      question: 'Word “BOUQUET” has vowels.',
      options: [
        {id: 'A', text: '3'},
        {id: 'B', text: '4'},
        {id: 'C', text: '1'},
        {id: 'D', text: '5'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vowels/33.jpeg'),
    },
    {
      question: 'Click the vowels of given picture.',
      options: [
        {id: 'A', text: 'A , O'},
        {id: 'B', text: 'A , I'},
        {id: 'C', text: 'O , I'},
        {id: 'D', text: 'E , U'},
      ],
      correctAnswer: 'C',
      image: require('../Utils/Images/Images/vowels/34.jpeg'),
    },
    {
      question: '“GHILLI SUIT” Has _ number of vowels.',
      options: [
        {id: 'A', text: '4'},
        {id: 'B', text: '5'},
        {id: 'C', text: '6'},
        {id: 'D', text: '7'},
      ],
      correctAnswer: 'A',
      image: require('../Utils/Images/Images/vowels/35.jpeg'),
    },
    {
      question: 'Last letter of picture.',
      options: [
        {id: 'A', text: 'U'},
        {id: 'B', text: 'I'},
        {id: 'C', text: 'O'},
        {id: 'D', text: 'E'},
      ],
      correctAnswer: 'A',
      image: require('../Utils/Images/Images/vowels/36.jpeg'),
    },
    {
      question: 'Silent vowel in “SLEDGE”.',
      options: [
        {id: 'A', text: 'D'},
        {id: 'B', text: 'E'},
        {id: 'C', text: 'I'},
        {id: 'D', text: 'G'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vowels/37.jpeg'),
    },
    {
      question: 'Count vowels in “SUBMARINE”.',
      options: [
        {id: 'A', text: '1'},
        {id: 'B', text: '2'},
        {id: 'C', text: '3'},
        {id: 'D', text: '4'},
      ],
      correctAnswer: 'D',
      image: require('../Utils/Images/Images/vowels/38.jpeg'),
    },
    {
      question: 'Which vowel has long sound “TRUMPET”.',
      options: [
        {id: 'A', text: 'U'},
        {id: 'B', text: 'R'},
        {id: 'C', text: 'E'},
        {id: 'D', text: 'A'},
      ],
      correctAnswer: 'C',
      image: require('../Utils/Images/Images/vowels/39.jpeg'),
    },
    {
      question: 'Count the vowels in “UTENSILS”.',
      options: [
        {id: 'A', text: '6'},
        {id: 'B', text: '3'},
        {id: 'C', text: '4'},
        {id: 'D', text: '5'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vowels/40.jpeg'),
    },
    {
      question: 'Silent vowel in “PEA”.',
      options: [
        {id: 'A', text: 'A'},
        {id: 'B', text: 'E'},
        {id: 'C', text: 'I'},
        {id: 'D', text: 'P'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vowels/41.jpeg'),
    },
    {
      question: 'Last vowel in “GLACIER”.',
      options: [
        {id: 'A', text: 'i'},
        {id: 'B', text: 'a'},
        {id: 'C', text: 'e'},
        {id: 'D', text: 'r'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vowels/42.jpeg'),
    },
    {
      question: 'Fill in the blank “Y_CHT”.',
      options: [
        {id: 'A', text: 'a'},
        {id: 'B', text: 'o'},
        {id: 'C', text: 'i'},
        {id: 'D', text: 'e'},
      ],
      correctAnswer: 'D',
      image: require('../Utils/Images/Images/vowels/43.jpeg'),
    },
  
];

export const prepositionQuestions = [
  {
    question: 'The fish is ___ the sea.',
    options: [
      { id: 'A', text: 'at' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'in' },
      { id: 'D', text: 'with' },
    ],
    correctAnswer: 'C',
    image: require('../Utils/Images/Images/prepositions/1.jpeg'),
  },
  {
    question: 'The ball is ___ the box.',
    options: [
      { id: 'A', text: 'on' },
      { id: 'B', text: 'under' },
      { id: 'C', text: 'between' },
      { id: 'D', text: 'at' },
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/prepositions/2.jpeg'),
  },
  {
    question: 'The chocolate is ___ the fridge.',
    options: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'under' },
      { id: 'D', text: 'between' },
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/prepositions/3.jpeg'),
  },
  {
    question: 'The boy jumped ___ the fence.',
    options: [
      { id: 'A', text: 'over' },
      { id: 'B', text: 'through' },
      { id: 'C', text: 'under' },
      { id: 'D', text: 'in' },
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/prepositions/4.jpeg'),
  },
  {
    question: 'The dog ran ___ the street.',
    options: [
      { id: 'A', text: 'on' },
      { id: 'B', text: 'across' },
      { id: 'C', text: 'beside' },
      { id: 'D', text: 'between' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/5.jpeg'),
  },
  {
    question: 'The cat is sitting ___ the roof.',
    options: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'under' },
      { id: 'D', text: 'over' },
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/prepositions/6.jpeg'),
  },
  {
    question: 'The school is located ___ the river.',
    options: [
      { id: 'A', text: 'beside' },
      { id: 'B', text: 'in' },
      { id: 'C', text: 'on' },
      { id: 'D', text: 'at' },
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/prepositions/7.jpeg'),
  },
  {
    question: 'The ball rolled ___ the hill.',
    options: [
      { id: 'A', text: 'up' },
      { id: 'B', text: 'down' },
      { id: 'C', text: 'beside' },
      { id: 'D', text: 'with' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/8.jpeg'),
  },
  {
    question: 'The treasure is hidden ___ the cave.',
    options: [
      { id: 'A', text: 'at' },
      { id: 'B', text: 'under' },
      { id: 'C', text: 'on' },
      { id: 'D', text: 'by' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/9.jpeg'),
  },
  {
    question: 'The books are ___ the shelf.',
    options: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'at' },
      { id: 'D', text: 'by' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/10.jpeg'),
  },
  {
    question: 'The picture is hanging ___ the wall.',
    options: [
      { id: 'A', text: 'at' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'in' },
      { id: 'D', text: 'with' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/11.jpeg'),
  },
  {
    question: 'The cat is hiding ___ the table.',
    options: [
      { id: 'A', text: 'at' },
      { id: 'B', text: 'in' },
      { id: 'C', text: 'under' },
      { id: 'D', text: 'with' },
    ],
    correctAnswer: 'C',
    image: require('../Utils/Images/Images/prepositions/12.jpeg'),
  },
  {
    question: 'The bird flew ___ the sky.',
    options: [
      { id: 'A', text: 'at' },
      { id: 'B', text: 'in' },
      { id: 'C', text: 'on' },
      { id: 'D', text: 'through' },
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/prepositions/13.jpeg'),
  },
  {
    question: 'The sun sets ___ the horizon.',
    options: [
      { id: 'A', text: 'at' },
      { id: 'B', text: 'in' },
      { id: 'C', text: 'on' },
      { id: 'D', text: 'over' },
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/prepositions/14.jpeg'),
  },
  {
    question: 'The playground is located ___ the school building.',
    options: [
      { id: 'A', text: 'at' },
      { id: 'B', text: 'in' },
      { id: 'C', text: 'beside' },
      { id: 'D', text: 'on' },
      { id: 'E', text: 'by' },
    ],
    correctAnswer: 'C',
    image: require('../Utils/Images/Images/prepositions/15.jpeg'),
  },
  {
    question: 'The squirrel is climbing ___ the tree.',
    options: [
      { id: 'A', text: 'on' },
      { id: 'B', text: 'at' },
      { id: 'C', text: 'in' },
      { id: 'D', text: 'up' },
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/prepositions/16.jpeg'),
  },
  {
    question: 'The river flows ___ the bridge.',
    options: [
      { id: 'A', text: 'under' },
      { id: 'B', text: 'over' },
      { id: 'C', text: 'at' },
      { id: 'D', text: 'in' },
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/prepositions/17.jpeg'),
  },
  {
    question: 'The children are playing ___ the playground.',
    options: [
      { id: 'A', text: 'at' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'in' },
      { id: 'D', text: 'with' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/18.jpeg'),
  },
  {
    question: 'The dog is hiding ___ the stairs.',
    options: [
      { id: 'A', text: 'at' },
      { id: 'B', text: 'in' },
      { id: 'C', text: 'under' },
      { id: 'D', text: 'with' },
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/prepositions/19.jpeg'),
  },
  {
    question: 'The butterfly landed ___ the flower.',
    options: [
      { id: 'A', text: 'at' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'in' },
      { id: 'D', text: 'with' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/20.jpeg'),
  },
  {
    question: 'The train travels ___ the tunnel.',
    options: [
      { id: 'A', text: 'through' },
      { id: 'B', text: 'in' },
      { id: 'C', text: 'at' },
      { id: 'D', text: 'by' },
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/prepositions/21.jpeg'),
  },
  {
    question: 'The cat is hiding ___ the blanket.',
    options: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'under' },
      { id: 'C', text: 'at' },
      { id: 'D', text: 'with' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/22.jpeg'),
  },
  {
    question: 'The sun sets ___ the mountains.',
    options: [
      { id: 'A', text: 'behind' },
      { id: 'B', text: 'at' },
      { id: 'C', text: 'on' },
      { id: 'D', text: 'in' },
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/prepositions/23.jpeg'),
  },
  {
    question: 'The river flows ___ the bridge.',
    options: [
      { id: 'A', text: 'under' },
      { id: 'B', text: 'over' },
      { id: 'C', text: 'at' },
      { id: 'D', text: 'in' },
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/prepositions/24.jpeg'),
  },
  {
    question: 'The bird is flying ___ the house.',
    options: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'under' },
      { id: 'D', text: 'beside' },
      { id: 'E', text: 'over' },
    ],
    correctAnswer: 'E',
    image: require('../Utils/Images/Images/prepositions/25.jpeg'),
  },
  {
    question: 'The clouds are ___ the mountain.',
    options: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'beside' },
      { id: 'D', text: 'over' },
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/prepositions/26.jpeg'),
  },
  {
    question: 'The bridge goes ___ the river.',
    options: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'under' },
      { id: 'D', text: 'beside' },
      { id: 'E', text: 'over' },
    ],
    correctAnswer: 'E',
    image: require('../Utils/Images/Images/prepositions/27.jpeg'),
  },
  {
    question: 'The plane is flying ___ the city.',
    options: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'under' },
      { id: 'D', text: 'beside' },
      { id: 'E', text: 'over' },
    ],
    correctAnswer: 'E',
    image: require('../Utils/Images/Images/prepositions/28.jpeg'),
  },
  {
    question: 'Cups are ___ the table.',
    options: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'under' },
      { id: 'D', text: 'beside' },
      { id: 'E', text: 'over' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/29.jpeg'),
  },
  {
    question: 'The boy is sitting ___ the sofa.',
    options: [
      { id: 'A', text: 'in' },
      { id: 'B', text: 'on' },
      { id: 'C', text: 'under' },
      { id: 'D', text: 'beside' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/30.jpeg'),
  },
  {
    question: 'The cat is ___ the window.',
    options: [
      { id: 'A', text: 'in front of' },
      { id: 'B', text: 'behind' },
      { id: 'C', text: 'beside' },
      { id: 'D', text: 'on' },
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/prepositions/31.jpeg'),
  },
  {
    question: 'The book is ___ the table.',
    options: [
      { id: 'A', text: 'on' },
      { id: 'B', text: 'under' },
      { id: 'C', text: 'between' },
      { id: 'D', text: 'at' },
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/prepositions/32.jpeg'),
  },
  {
    question: 'The kangaroo is ___ the forest.',
    options: [
      { id: 'A', text: 'on' },
      { id: 'B', text: 'under' },
      { id: 'C', text: 'between' },
      { id: 'D', text: 'in' },
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/prepositions/33.jpeg'),
  },
];

export const vocabularyQuestions = [
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Furtive'},
      {id: 'B', text: 'Fartive'},
      {id: 'C', text: 'Farteev'},
      {id: 'D', text: 'Fertive'},
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/vocabulary/1.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Quokaa'},
      {id: 'B', text: 'Kokka'},
      {id: 'C', text: 'Kwokka'},
      {id: 'D', text: 'Quokka'},
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/vocabulary/2.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Teleskope'},
      {id: 'B', text: 'Telescope'},
      {id: 'C', text: 'Telaskope'},
      {id: 'D', text: 'Telascope'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vocabulary/3.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Rokkett'},
      {id: 'B', text: 'Roket'},
      {id: 'C', text: 'Roacket'},
      {id: 'D', text: 'Rocket'},
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/vocabulary/4.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Dinosaur'},
      {id: 'B', text: 'Dinosor'},
      {id: 'C', text: 'Dinasaur'},
      {id: 'D', text: 'Dynosaur'},
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/vocabulary/5.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Girraff'},
      {id: 'B', text: 'Giraffe'},
      {id: 'C', text: 'Girafe'},
      {id: 'D', text: 'Giraff'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vocabulary/6.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Cactus'},
      {id: 'B', text: 'Cactuss'},
      {id: 'C', text: 'Kaktus'},
      {id: 'D', text: 'Caktus'},
    ],
    correctAnswer: 'A',
    image: require('../Utils/Images/Images/vocabulary/7.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Karousell'},
      {id: 'B', text: 'Carousell'},
      {id: 'C', text: 'Karousel'},
      {id: 'D', text: 'Carousel'},
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/vocabulary/8.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Magnifing Glass'},
      {id: 'B', text: 'Magniying Glass'},
      {id: 'C', text: 'Magnifying Glass'},
      {id: 'D', text: 'Magnifing Glas'},
    ],
    correctAnswer: 'C',
    image: require('../Utils/Images/Images/vocabulary/9.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Ennigma'},
      {id: 'B', text: 'Enigma'},
      {id: 'C', text: 'Enigme'},
      {id: 'D', text: 'Inigma'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vocabulary/10.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Pengwin'},
      {id: 'B', text: 'Penguine'},
      {id: 'C', text: 'Penguin'},
      {id: 'D', text: 'Penguinn'},
    ],
    correctAnswer: 'C',
    image: require('../Utils/Images/Images/vocabulary/11.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Narwall'},
      {id: 'B', text: 'Narwhal'},
      {id: 'C', text: 'Narwhall'},
      {id: 'D', text: 'Narwhaal'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vocabulary/12.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Xylophone'},
      {id: 'B', text: 'Xilophone'},
      {id: 'C', text: 'Xylaphon'},
      {id: 'D', text: 'Xylaphone'},
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/vocabulary/13.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Labratory'},
      {id: 'B', text: 'Laboratory'},
      {id: 'C', text: 'Laborotory'},
      {id: 'D', text: 'Laboratary'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vocabulary/14.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Lemonaid'},
      {id: 'B', text: 'Limonadee'},
      {id: 'C', text: 'Lemonade'},
      {id: 'D', text: 'Limonade'},
    ],
    correctAnswer: 'C',
    image: require('../Utils/Images/Images/vocabulary/15.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Volcanno'},
      {id: 'B', text: 'Volcannoe'},
      {id: 'C', text: 'Volcaano'},
      {id: 'D', text: 'Volcano'},
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/vocabulary/16.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Wizarrd'},
      {id: 'B', text: 'Wizzard'},
      {id: 'C', text: 'Wizad'},
      {id: 'D', text: 'Wizard'},
    ],
    correctAnswer: 'D',
    image: require('../Utils/Images/Images/vocabulary/17.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Sailng Boat'},
      {id: 'B', text: 'Sailing Boat'},
      {id: 'C', text: 'Sail Boat'},
      {id: 'D', text: 'Saling Boat'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vocabulary/18.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Iccicle'},
      {id: 'B', text: 'Icicle'},
      {id: 'C', text: 'Icycle'},
      {id: 'D', text: 'Icicel'},
    ],
    correctAnswer: 'B',
    image: require('../Utils/Images/Images/vocabulary/19.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Hammok'},
      {id: 'B', text: 'Hammok'},
      {id: 'C', text: 'Hammock'},
      {id: 'D', text: 'Hammockk'},
    ],
    correctAnswer: 'C',
    image: require('../Utils/Images/Images/vocabulary/20.png'),
  },
  {
    question: 'Select the correct vocabulary option:',
    options: [
      {id: 'A', text: 'Umbrella'},
      {id: 'B', text: 'Umbralla'},
      {id: 'C', text: 'Umrella'},
      {id: 'D', text: 'Umbrela'},
    ],
      correctAnswer: 'A',
      image: require('../Utils/Images/Images/vocabulary/21.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Skatebord'},
        {id: 'B', text: 'Skateboard'},
        {id: 'C', text: 'Skateborde'},
        {id: 'D', text: 'Skatebaord'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vocabulary/22.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Kaleidoscope'},
        {id: 'B', text: 'Kaliedoscope'},
        {id: 'C', text: 'Kaleidoskope'},
        {id: 'D', text: 'Kaledoscope'},
      ],
      correctAnswer: 'A',
      image: require('../Utils/Images/Images/vocabulary/23.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Termometer'},
        {id: 'B', text: 'Thermometer'},
        {id: 'C', text: 'Thermomter'},
        {id: 'D', text: 'Thermometre'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vocabulary/24.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Submarin'},
        {id: 'B', text: 'Submarinne'},
        {id: 'C', text: 'Submarine'},
        {id: 'D', text: 'Submerine'},
      ],
      correctAnswer: 'C',
      image: require('../Utils/Images/Images/vocabulary/25.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Marigold'},
        {id: 'B', text: 'Marigolde'},
        {id: 'C', text: 'Marygold'},
        {id: 'D', text: 'Marigald'},
      ],
      correctAnswer: 'A',
      image: require('../Utils/Images/Images/vocabulary/27.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Ukuleele'},
        {id: 'B', text: 'Ukulelee'},
        {id: 'C', text: 'Ukulele'},
        {id: 'D', text: 'Ukelele'},
      ],
      correctAnswer: 'C',
      image: require('../Utils/Images/Images/vocabulary/27.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Frizbee'},
        {id: 'B', text: 'Frisbee'},
        {id: 'C', text: 'Frisby'},
        {id: 'D', text: 'Frisbbee'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vocabulary/28.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Microscop'},
        {id: 'B', text: 'Microscope'},
        {id: 'C', text: 'Microskope'},
        {id: 'D', text: 'Microscoppe'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vocabulary/29.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Lighthous'},
        {id: 'B', text: 'Lightouse'},
        {id: 'C', text: 'Lighthosse'},
        {id: 'D', text: 'Lighthouse'},
      ],
      correctAnswer: 'D',
      image: require('../Utils/Images/Images/vocabulary/30.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Chandellier'},
        {id: 'B', text: 'Chandelier'},
        {id: 'C', text: 'Chandeleer'},
        {id: 'D', text: 'Chandelir'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vocabulary/31.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Binoculars'},
        {id: 'B', text: 'Binoculors'},
        {id: 'C', text: 'Binoculers'},
        {id: 'D', text: 'Binocularrs'},
      ],
      correctAnswer: 'A',
      image: require('../Utils/Images/Images/vocabulary/32.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Tooster'},
        {id: 'B', text: 'Toaster'},
        {id: 'C', text: 'Toarster'},
        {id: 'D', text: 'Toastar'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vocabulary/33.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Saxaphone'},
        {id: 'B', text: 'Saxofone'},
        {id: 'C', text: 'Saxophone'},
        {id: 'D', text: 'Saxaphon'},
      ],
      correctAnswer: 'C',
      image: require('../Utils/Images/Images/vocabulary/34.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Parachute'},
        {id: 'B', text: 'Parachoot'},
        {id: 'C', text: 'Parashute'},
        {id: 'D', text: 'Parachote'},
      ],
      correctAnswer: 'A',
      image: require('../Utils/Images/Images/vocabulary/35.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Sunglases'},
        {id: 'B', text: 'Sunglasses'},
        {id: 'C', text: 'Sunnglasses'},
        {id: 'D', text: 'Sunglassess'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vocabulary/36.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Iggloo'},
        {id: 'B', text: 'Iglow'},
        {id: 'C', text: 'Igloo'},
        {id: 'D', text: 'Iglee'},
      ],
      correctAnswer: 'C',
      image: require('../Utils/Images/Images/vocabulary/37.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Gloove'},
        {id: 'B', text: 'Glove'},
        {id: 'C', text: 'Glov'},
        {id: 'D', text: 'Glouve'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vocabulary/38.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Suitecase'},
        {id: 'B', text: 'Suitcase'},
        {id: 'C', text: 'Suitcasse'},
        {id: 'D', text: 'Suitcas'},
      ],
      correctAnswer: 'B',
      image: require('../Utils/Images/Images/vocabulary/39.jpeg'),
    },
    {
      question: 'Select the correct vocabulary option:',
      options: [
        {id: 'A', text: 'Hourglasse'},
        {id: 'B', text: 'Hourglaas'},
        {id: 'C', text: 'Hourglase'},
        {id: 'D', text: 'Hourglass'},
      ],
      correctAnswer: 'D',
      image: require('../Utils/Images/Images/vocabulary/40.jpeg'),
    },
  ];
  
   

